global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 60s
scrape_configs:
  - job_name: goplus-avs
    honor_timestamps: true
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:${API_PORT}']