{
 "title": "Goplus AVS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Task handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "clamp_min(sum by(operator_pk) (delta(avs_operator_num_task_handled[5m])),0)  or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task duration P50 ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time(avs_operator_task_handled_duration{quantile=\"0.5\"}[5m])) by (operator_pk) * 1000  or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "clamp_min(sum by(operator_pk) (delta(avs_operator_num_task_failed[5m])),0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task duration P90 ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(avg_over_time(avs_operator_task_handled_duration{quantile=\"0.9\"}[5m])) by (operator_pk) * 1000  or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running secware",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(operator_pk) (avs_operator_secware_num)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health report 1H",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, job) (increase(avs_operator_num_health_reported[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secware sync 1H",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, job)(increase(avs_operator_num_secware_synced[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task duration P99 ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(avg_over_time(avs_operator_task_handled_duration{quantile=\"0.99\"}[5m])) by (operator_pk) * 1000  or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}